#!/usr/bin/env bash

#chown daemon /var/www/html -R
#chown nobody:nogroup /var/www/html -R
chown www-data /var/www/html -R
chmod u=rx,go= /var/www/html -R
chmod u+w /var/www/html/{config,data,apps} -R

# register with etcd
ID=`hostname -s`
IP=`hostname -i`
JSON={\"id\":\"${ID}\",\"ip\":\"${IP}\"}
curl -XPUT http://etcd:4001/v2/keys/owncloud -d dir=true
#curl -XPUT http://etcd:4001/v2/keys/owncloud/${ID} -d dir=true
# curl -XPUT http://etcd:4001/v2/keys/owncloud/${ID} -d value=${IP}
#curl -XPUT http://etcd:4001/v2/keys/owncloud/${ID} -d value={"id":"${ID}","ip":"${IP}"}
curl -XPUT http://etcd:4001/v2/keys/owncloud/${ID} -d value=${JSON}



exec apache2 -DFOREGROUND
#exec httpd -DFOREGROUND
